# DO NOT EDIT THIS FILE.
# Generated from Iuliia schemas. See `Iuliia::SchemaImporter`.

require "../engine"

module Iuliia
  # The `Gost52290` module provides transliteration (`Engine.translate`) using
  # the GOST R 52290-2004 transliteration schema.
  #
  # [More information](https://dangry.ru/iuliia/gost-52290/) (in Russian)
  #
  # ### Examples
  #
  # ```
  # Iuliia::Gost52290.translate("Россия, город Йошкар-Ола, улица Яна Крастыня")
  # # => "Rossiya, gorod Yoshkar-Ola, ulitsa Yana Krastynya"
  #
  # Iuliia::Gost52290.translate("Юлия, съешь ещё этих мягких французских булок из Йошкар-Олы, да выпей алтайского чаю")
  # # => "Yuliya, syesh' eshche etikh myagkikh frantsuzskikh bulok iz Yoshkar-Oly, da vypey altayskogo chayu"
  #
  # Iuliia::Gost52290.translate("Ё Крё Мякоё")
  # # => "Yo Krye Myakoyo"
  # ```
  module Gost52290
    include Iuliia::Engine
    extend self

    private NAME        = "gost_52290"
    private DESCRIPTION = "GOST R 52290-2004 transliteration schema"

    private STANDARD_RULES_MAPPING = {
      "а" => "a",
      "б" => "b",
      "в" => "v",
      "г" => "g",
      "д" => "d",
      "е" => "e",
      "ё" => "yo",
      "ж" => "zh",
      "з" => "z",
      "и" => "i",
      "й" => "y",
      "к" => "k",
      "л" => "l",
      "м" => "m",
      "н" => "n",
      "о" => "o",
      "п" => "p",
      "р" => "r",
      "с" => "s",
      "т" => "t",
      "у" => "u",
      "ф" => "f",
      "х" => "kh",
      "ц" => "ts",
      "ч" => "ch",
      "ш" => "sh",
      "щ" => "shch",
      "ъ" => "'",
      "ы" => "y",
      "ь" => "'",
      "э" => "e",
      "ю" => "yu",
      "я" => "ya",
      "А" => "A",
      "Б" => "B",
      "В" => "V",
      "Г" => "G",
      "Д" => "D",
      "Е" => "E",
      "Ё" => "Yo",
      "Ж" => "Zh",
      "З" => "Z",
      "И" => "I",
      "Й" => "Y",
      "К" => "K",
      "Л" => "L",
      "М" => "M",
      "Н" => "N",
      "О" => "O",
      "П" => "P",
      "Р" => "R",
      "С" => "S",
      "Т" => "T",
      "У" => "U",
      "Ф" => "F",
      "Х" => "Kh",
      "Ц" => "Ts",
      "Ч" => "Ch",
      "Ш" => "Sh",
      "Щ" => "Shch",
      "Ъ" => "'",
      "Ы" => "Y",
      "Ь" => "'",
      "Э" => "E",
      "Ю" => "Yu",
      "Я" => "Ya",
    }
    private PREVIOUS_CHARACTERS_RULES_MAPPING = {
      "ае" => "ye",
      "ее" => "ye",
      "ёе" => "ye",
      "ие" => "ye",
      "ое" => "ye",
      "уе" => "ye",
      "ъе" => "ye",
      "ые" => "ye",
      "ье" => "ye",
      "эе" => "ye",
      "юе" => "ye",
      "яе" => "ye",
      "бё" => "ye",
      "вё" => "ye",
      "гё" => "ye",
      "дё" => "ye",
      "зё" => "ye",
      "кё" => "ye",
      "лё" => "ye",
      "мё" => "ye",
      "нё" => "ye",
      "пё" => "ye",
      "рё" => "ye",
      "сё" => "ye",
      "тё" => "ye",
      "фё" => "ye",
      "хё" => "ye",
      "цё" => "ye",
      "жё" => "e",
      "чё" => "e",
      "шё" => "e",
      "щё" => "e",
      "Ае" => "ye",
      "Ее" => "ye",
      "Ёе" => "ye",
      "Ие" => "ye",
      "Ое" => "ye",
      "Уе" => "ye",
      "Ъе" => "ye",
      "Ые" => "ye",
      "Ье" => "ye",
      "Эе" => "ye",
      "Юе" => "ye",
      "Яе" => "ye",
      "Бё" => "ye",
      "Вё" => "ye",
      "Гё" => "ye",
      "Дё" => "ye",
      "Зё" => "ye",
      "Кё" => "ye",
      "Лё" => "ye",
      "Мё" => "ye",
      "Нё" => "ye",
      "Пё" => "ye",
      "Рё" => "ye",
      "Сё" => "ye",
      "Тё" => "ye",
      "Фё" => "ye",
      "Хё" => "ye",
      "Цё" => "ye",
      "Жё" => "e",
      "Чё" => "e",
      "Шё" => "e",
      "Щё" => "e",
      "АЕ" => "Ye",
      "ЕЕ" => "Ye",
      "ЁЕ" => "Ye",
      "ИЕ" => "Ye",
      "ОЕ" => "Ye",
      "УЕ" => "Ye",
      "ЪЕ" => "Ye",
      "ЫЕ" => "Ye",
      "ЬЕ" => "Ye",
      "ЭЕ" => "Ye",
      "ЮЕ" => "Ye",
      "ЯЕ" => "Ye",
      "БЁ" => "Ye",
      "ВЁ" => "Ye",
      "ГЁ" => "Ye",
      "ДЁ" => "Ye",
      "ЗЁ" => "Ye",
      "КЁ" => "Ye",
      "ЛЁ" => "Ye",
      "МЁ" => "Ye",
      "НЁ" => "Ye",
      "ПЁ" => "Ye",
      "РЁ" => "Ye",
      "СЁ" => "Ye",
      "ТЁ" => "Ye",
      "ФЁ" => "Ye",
      "ХЁ" => "Ye",
      "ЦЁ" => "Ye",
      "ЖЁ" => "E",
      "ЧЁ" => "E",
      "ШЁ" => "E",
      "ЩЁ" => "E",
    }
    private NEXT_CHARACTERS_RULES_MAPPING = {
      "ъе" => "",
      "ье" => "",
      "ъё" => "",
      "ьё" => "",
      "ЪЕ" => "",
      "ЬЕ" => "",
      "ЪЁ" => "",
      "ЬЁ" => "",
      "Ъе" => "",
      "Ье" => "",
      "Ъё" => "",
      "Ьё" => "",
    }
    private SPECIAL_WORD_ENDINGS_RULES_MAPPING = {} of String => String

    # Returns the transliteration schema **name**.
    def name : String
      NAME
    end

    # Returns the transliteration schema **description**.
    def description : String
      DESCRIPTION
    end

    private def standard_rules_mapping : Hash(String, String)
      STANDARD_RULES_MAPPING
    end

    private def previous_characters_rules_mapping : Hash(String, String)
      PREVIOUS_CHARACTERS_RULES_MAPPING
    end

    private def next_characters_rules_mapping : Hash(String, String)
      NEXT_CHARACTERS_RULES_MAPPING
    end

    private def special_word_endings_rules_mapping : Hash(String, String)
      SPECIAL_WORD_ENDINGS_RULES_MAPPING
    end
  end
end
