# DO NOT EDIT THIS FILE.
# Generated from Iuliia schemas. See `Iuliia::SchemaImporter`.

require "../engine"

module Iuliia
  # The `Mosmetro` module provides transliteration (`.translate`) using
  # the Moscow Metro map transliteration schema.
  #
  # ### Examples
  #
  # ```
  # Iuliia::Mosmetro.translate("Юлия, съешь ещё этих мягких французских булок из Йошкар-Олы, да выпей алтайского чаю")
  # # => "Yuliya, syesh esche etikh myagkikh frantsuzskikh bulok iz Yoshkar-Oly, da vypey altayskogo chayu"
  #
  # Iuliia::Mosmetro.translate("Битцевский парк")
  # # => "Bitsevsky park"
  #
  # Iuliia::Mosmetro.translate("Верхние Лихоборы")
  # # => "Verkhnie Likhobory"
  #
  # Iuliia::Mosmetro.translate("Воробьёвы горы")
  # # => "Vorobyovy gory"
  #
  # Iuliia::Mosmetro.translate("Выхино")
  # # => "Vykhino"
  #
  # Iuliia::Mosmetro.translate("Зябликово")
  # # => "Zyablikovo"
  #
  # Iuliia::Mosmetro.translate("Измайловская")
  # # => "Izmaylovskaya"
  #
  # Iuliia::Mosmetro.translate("Кожуховская")
  # # => "Kozhukhovskaya"
  #
  # Iuliia::Mosmetro.translate("Крылатское")
  # # => "Krylatskoe"
  #
  # Iuliia::Mosmetro.translate("Марьина Роща")
  # # => "Maryina Roscha"
  #
  # Iuliia::Mosmetro.translate("Марьино")
  # # => "Maryino"
  #
  # Iuliia::Mosmetro.translate("Молодёжная")
  # # => "Molodezhnaya"
  #
  # Iuliia::Mosmetro.translate("Октябрьская")
  # # => "Oktyabrskaya"
  #
  # Iuliia::Mosmetro.translate("Ольховая")
  # # => "Olkhovaya"
  #
  # Iuliia::Mosmetro.translate("Парк Победы")
  # # => "Park Pobedy"
  #
  # Iuliia::Mosmetro.translate("Площадь Ильича")
  # # => "Ploschad Ilyicha"
  #
  # Iuliia::Mosmetro.translate("Площадь Революции")
  # # => "Ploschad Revolyutsii"
  #
  # Iuliia::Mosmetro.translate("Пятницкое шоссе")
  # # => "Pyatnitskoe shosse"
  #
  # Iuliia::Mosmetro.translate("Румянцево")
  # # => "Rumyantsevo"
  #
  # Iuliia::Mosmetro.translate("Саларьево")
  # # => "Salaryevo"
  #
  # Iuliia::Mosmetro.translate("Семёновская")
  # # => "Semenovskaya"
  #
  # Iuliia::Mosmetro.translate("Сходненская")
  # # => "Skhodnenskaya"
  #
  # Iuliia::Mosmetro.translate("Текстильщики")
  # # => "Tekstilschiki"
  #
  # Iuliia::Mosmetro.translate("Тёплый стан")
  # # => "Teply stan"
  #
  # Iuliia::Mosmetro.translate("Третьяковская")
  # # => "Tretyakovskaya"
  #
  # Iuliia::Mosmetro.translate("Тропарёво")
  # # => "Troparevo"
  #
  # Iuliia::Mosmetro.translate("Фонвизинская")
  # # => "Fonvizinskaya"
  #
  # Iuliia::Mosmetro.translate("Чистые пруды")
  # # => "Chistye prudy"
  #
  # Iuliia::Mosmetro.translate("Шоссе Энтузиастов")
  # # => "Shosse Entuziastov"
  #
  # Iuliia::Mosmetro.translate("Щёлковская")
  # # => "Schelkovskaya"
  #
  # Iuliia::Mosmetro.translate("Электрозаводская")
  # # => "Elektrozavodskaya"
  #
  # Iuliia::Mosmetro.translate("Юго-Западная")
  # # => "Yugo-Zapadnaya"
  # ```
  module Mosmetro
    include Iuliia::Engine
    extend self

    private NAME        = "mosmetro"
    private DESCRIPTION = "Moscow Metro map transliteration schema"

    private STANDARD_RULES_MAPPING = {
      "а" => "a",
      "б" => "b",
      "в" => "v",
      "г" => "g",
      "д" => "d",
      "е" => "e",
      "ё" => "e",
      "ж" => "zh",
      "з" => "z",
      "и" => "i",
      "й" => "y",
      "к" => "k",
      "л" => "l",
      "м" => "m",
      "н" => "n",
      "о" => "o",
      "п" => "p",
      "р" => "r",
      "с" => "s",
      "т" => "t",
      "у" => "u",
      "ф" => "f",
      "х" => "kh",
      "ц" => "ts",
      "ч" => "ch",
      "ш" => "sh",
      "щ" => "sch",
      "ъ" => "",
      "ы" => "y",
      "ь" => "",
      "э" => "e",
      "ю" => "yu",
      "я" => "ya",
      "А" => "A",
      "Б" => "B",
      "В" => "V",
      "Г" => "G",
      "Д" => "D",
      "Е" => "E",
      "Ё" => "E",
      "Ж" => "Zh",
      "З" => "Z",
      "И" => "I",
      "Й" => "Y",
      "К" => "K",
      "Л" => "L",
      "М" => "M",
      "Н" => "N",
      "О" => "O",
      "П" => "P",
      "Р" => "R",
      "С" => "S",
      "Т" => "T",
      "У" => "U",
      "Ф" => "F",
      "Х" => "Kh",
      "Ц" => "Ts",
      "Ч" => "Ch",
      "Ш" => "Sh",
      "Щ" => "Sch",
      "Ъ" => "",
      "Ы" => "Y",
      "Ь" => "",
      "Э" => "E",
      "Ю" => "Yu",
      "Я" => "Ya",
    }
    private PREVIOUS_CHARACTERS_RULES_MAPPING = {
      "тц" => "s",
      "ьё" => "o",
      "ъё" => "o",
      "Тц" => "s",
      "Ьё" => "o",
      "Ъё" => "o",
      "ТЦ" => "S",
      "ЬЁ" => "O",
      "ЪЁ" => "O",
    }
    private NEXT_CHARACTERS_RULES_MAPPING = {
      "ьа" => "y",
      "ье" => "y",
      "ьё" => "y",
      "ьи" => "y",
      "ьо" => "y",
      "ьу" => "y",
      "ьэ" => "y",
      "ъа" => "y",
      "ъе" => "y",
      "ъё" => "y",
      "ъи" => "y",
      "ъо" => "y",
      "ъу" => "y",
      "ъэ" => "y",
      "ЬА" => "Y",
      "ЬЕ" => "Y",
      "ЬЁ" => "Y",
      "ЬИ" => "Y",
      "ЬО" => "Y",
      "ЬУ" => "Y",
      "ЬЭ" => "Y",
      "ЪА" => "Y",
      "ЪЕ" => "Y",
      "ЪЁ" => "Y",
      "ЪИ" => "Y",
      "ЪО" => "Y",
      "ЪУ" => "Y",
      "ЪЭ" => "Y",
      "Ьа" => "Y",
      "Ье" => "Y",
      "Ьё" => "Y",
      "Ьи" => "Y",
      "Ьо" => "Y",
      "Ьу" => "Y",
      "Ьэ" => "Y",
      "Ъа" => "Y",
      "Ъе" => "Y",
      "Ъё" => "Y",
      "Ъи" => "Y",
      "Ъо" => "Y",
      "Ъу" => "Y",
      "Ъэ" => "Y",
    }
    private SPECIAL_WORD_ENDINGS_RULES_MAPPING = {
      "ий" => "y",
      "ый" => "y",
      "Ий" => "Y",
      "Ый" => "Y",
      "ИЙ" => "Y",
      "ЫЙ" => "Y",
    }

    # Returns the transliteration schema **name**.
    def name : String
      NAME
    end

    # Returns the transliteration schema **description**.
    def description : String
      DESCRIPTION
    end

    private def standard_rules_mapping : Hash(String, String)
      STANDARD_RULES_MAPPING
    end

    private def previous_characters_rules_mapping : Hash(String, String)
      PREVIOUS_CHARACTERS_RULES_MAPPING
    end

    private def next_characters_rules_mapping : Hash(String, String)
      NEXT_CHARACTERS_RULES_MAPPING
    end

    private def special_word_endings_rules_mapping : Hash(String, String)
      SPECIAL_WORD_ENDINGS_RULES_MAPPING
    end
  end
end
