# Generated from Iuliia schemas. See `Iuliia::SchemaImporter`.
# 2022-01-09 03:48:22 UTC
#
# DO NOT edit this file directly.

require "../engine"

module Iuliia
  module Scientific
    include Iuliia::Engine
    extend self

    NAME        = "scientific"
    DESCRIPTION = "Scientific transliteration schema"

    STANDARD_RULES_MAPPING = {
      "а" => "a",
      "б" => "b",
      "в" => "v",
      "г" => "g",
      "д" => "d",
      "е" => "e",
      "ё" => "ё",
      "ж" => "ž",
      "з" => "z",
      "и" => "i",
      "й" => "j",
      "к" => "k",
      "л" => "l",
      "м" => "m",
      "н" => "n",
      "о" => "o",
      "п" => "p",
      "р" => "r",
      "с" => "s",
      "т" => "t",
      "у" => "u",
      "ф" => "f",
      "х" => "x",
      "ц" => "c",
      "ч" => "č",
      "ш" => "š",
      "щ" => "šč",
      "ъ" => "ʺ",
      "ы" => "y",
      "ь" => "ʹ",
      "э" => "è",
      "ю" => "ju",
      "я" => "ja",
      "А" => "A",
      "Б" => "B",
      "В" => "V",
      "Г" => "G",
      "Д" => "D",
      "Е" => "E",
      "Ё" => "Ё",
      "Ж" => "Ž",
      "З" => "Z",
      "И" => "I",
      "Й" => "J",
      "К" => "K",
      "Л" => "L",
      "М" => "M",
      "Н" => "N",
      "О" => "O",
      "П" => "P",
      "Р" => "R",
      "С" => "S",
      "Т" => "T",
      "У" => "U",
      "Ф" => "F",
      "Х" => "X",
      "Ц" => "C",
      "Ч" => "Č",
      "Ш" => "Š",
      "Щ" => "Šč",
      "Ъ" => "ʺ",
      "Ы" => "Y",
      "Ь" => "ʹ",
      "Э" => "È",
      "Ю" => "Ju",
      "Я" => "Ja",
    }
    PREVIOUS_CHARACTERS_RULES_MAPPING  = {} of String => String
    NEXT_CHARACTERS_RULES_MAPPING      = {} of String => String
    SPECIAL_WORD_ENDINGS_RULES_MAPPING = {} of String => String

    def description : String
      DESCRIPTION
    end

    private def standard_rules_mapping : Hash(String, String)
      STANDARD_RULES_MAPPING
    end

    private def previous_characters_rules_mapping : Hash(String, String)
      PREVIOUS_CHARACTERS_RULES_MAPPING
    end

    private def next_characters_rules_mapping : Hash(String, String)
      NEXT_CHARACTERS_RULES_MAPPING
    end

    private def special_word_endings_rules_mapping : Hash(String, String)
      SPECIAL_WORD_ENDINGS_RULES_MAPPING
    end
  end
end
