# Generated from Iuliia schemas. See `Iuliia::SchemaImporter`.
# 2022-01-09 03:48:22 UTC
#
# DO NOT edit this file directly.

require "../engine"

module Iuliia
  module Wikipedia
    include Iuliia::Engine
    extend self

    NAME        = "wikipedia"
    DESCRIPTION = "Wikipedia transliteration schema"

    STANDARD_RULES_MAPPING = {
      "а" => "a",
      "б" => "b",
      "в" => "v",
      "г" => "g",
      "д" => "d",
      "е" => "e",
      "ё" => "yo",
      "ж" => "zh",
      "з" => "z",
      "и" => "i",
      "й" => "y",
      "к" => "k",
      "л" => "l",
      "м" => "m",
      "н" => "n",
      "о" => "o",
      "п" => "p",
      "р" => "r",
      "с" => "s",
      "т" => "t",
      "у" => "u",
      "ф" => "f",
      "х" => "kh",
      "ц" => "ts",
      "ч" => "ch",
      "ш" => "sh",
      "щ" => "shch",
      "ъ" => "",
      "ы" => "y",
      "ь" => "",
      "э" => "e",
      "ю" => "yu",
      "я" => "ya",
      "А" => "A",
      "Б" => "B",
      "В" => "V",
      "Г" => "G",
      "Д" => "D",
      "Е" => "E",
      "Ё" => "Yo",
      "Ж" => "Zh",
      "З" => "Z",
      "И" => "I",
      "Й" => "Y",
      "К" => "K",
      "Л" => "L",
      "М" => "M",
      "Н" => "N",
      "О" => "O",
      "П" => "P",
      "Р" => "R",
      "С" => "S",
      "Т" => "T",
      "У" => "U",
      "Ф" => "F",
      "Х" => "Kh",
      "Ц" => "Ts",
      "Ч" => "Ch",
      "Ш" => "Sh",
      "Щ" => "Shch",
      "Ъ" => "",
      "Ы" => "Y",
      "Ь" => "",
      "Э" => "E",
      "Ю" => "Yu",
      "Я" => "Ya",
    }
    PREVIOUS_CHARACTERS_RULES_MAPPING = {
      "е"  => "ye",
      "ае" => "ye",
      "ие" => "ye",
      "ое" => "ye",
      "уе" => "ye",
      "эе" => "ye",
      "юе" => "ye",
      "яе" => "ye",
      "ье" => "ye",
      "ъе" => "ye",
      "Е"  => "Ye",
      "Ае" => "ye",
      "Ие" => "ye",
      "Ое" => "ye",
      "Уе" => "ye",
      "Эе" => "ye",
      "Юе" => "ye",
      "Яе" => "ye",
      "Ье" => "ye",
      "Ъе" => "ye",
      "АЕ" => "Ye",
      "ИЕ" => "Ye",
      "ОЕ" => "Ye",
      "УЕ" => "Ye",
      "ЭЕ" => "Ye",
      "ЮЕ" => "Ye",
      "ЯЕ" => "Ye",
      "ЬЕ" => "Ye",
      "ЪЕ" => "Ye",
    }
    NEXT_CHARACTERS_RULES_MAPPING = {
      "ъа" => "y",
      "ъи" => "y",
      "ъо" => "y",
      "ъу" => "y",
      "ъы" => "y",
      "ъэ" => "y",
      "ьа" => "y",
      "ьи" => "y",
      "ьо" => "y",
      "ьу" => "y",
      "ьы" => "y",
      "ьэ" => "y",
      "ЪА" => "Y",
      "ЪИ" => "Y",
      "ЪО" => "Y",
      "ЪУ" => "Y",
      "ЪЫ" => "Y",
      "ЪЭ" => "Y",
      "ЬА" => "Y",
      "ЬИ" => "Y",
      "ЬО" => "Y",
      "ЬУ" => "Y",
      "ЬЫ" => "Y",
      "ЬЭ" => "Y",
      "Ъа" => "Y",
      "Ъи" => "Y",
      "Ъо" => "Y",
      "Ъу" => "Y",
      "Ъы" => "Y",
      "Ъэ" => "Y",
      "Ьа" => "Y",
      "Ьи" => "Y",
      "Ьо" => "Y",
      "Ьу" => "Y",
      "Ьы" => "Y",
      "Ьэ" => "Y",
    }
    SPECIAL_WORD_ENDINGS_RULES_MAPPING = {
      "ий" => "y",
      "ый" => "y",
      "Ий" => "Y",
      "Ый" => "Y",
      "ИЙ" => "Y",
      "ЫЙ" => "Y",
    }

    def description : String
      DESCRIPTION
    end

    private def standard_rules_mapping : Hash(String, String)
      STANDARD_RULES_MAPPING
    end

    private def previous_characters_rules_mapping : Hash(String, String)
      PREVIOUS_CHARACTERS_RULES_MAPPING
    end

    private def next_characters_rules_mapping : Hash(String, String)
      NEXT_CHARACTERS_RULES_MAPPING
    end

    private def special_word_endings_rules_mapping : Hash(String, String)
      SPECIAL_WORD_ENDINGS_RULES_MAPPING
    end
  end
end
