# Generated from Iuliia schemas. See `Iuliia::SchemaImporter`.
# 2022-01-09 03:48:22 UTC
#
# DO NOT edit this file directly.
#
# ----------------------------------------------------------------------------
# Iuliia
# https://github.com/nalgeon/iuliia
# ----------------------------------------------------------------------------
#
# MIT License
#
# Copyright (c) 2020 Anton Zhiyanov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

require "../spec_helper"

describe Iuliia::Mosmetro do
  it "transliterates Юлия, съешь ещё этих мягких французских булок из Йошкар-Олы, да выпей алтайского чаю" do
    cyrilic = "Юлия, съешь ещё этих мягких французских булок из Йошкар-Олы, да выпей алтайского чаю"
    transliteration = "Yuliya, syesh esche etikh myagkikh frantsuzskikh bulok iz Yoshkar-Oly, da vypey altayskogo chayu"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Битцевский парк" do
    cyrilic = "Битцевский парк"
    transliteration = "Bitsevsky park"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Верхние Лихоборы" do
    cyrilic = "Верхние Лихоборы"
    transliteration = "Verkhnie Likhobory"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Воробьёвы горы" do
    cyrilic = "Воробьёвы горы"
    transliteration = "Vorobyovy gory"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Выхино" do
    cyrilic = "Выхино"
    transliteration = "Vykhino"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Зябликово" do
    cyrilic = "Зябликово"
    transliteration = "Zyablikovo"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Измайловская" do
    cyrilic = "Измайловская"
    transliteration = "Izmaylovskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Кожуховская" do
    cyrilic = "Кожуховская"
    transliteration = "Kozhukhovskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Крылатское" do
    cyrilic = "Крылатское"
    transliteration = "Krylatskoe"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Марьина Роща" do
    cyrilic = "Марьина Роща"
    transliteration = "Maryina Roscha"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Марьино" do
    cyrilic = "Марьино"
    transliteration = "Maryino"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Молодёжная" do
    cyrilic = "Молодёжная"
    transliteration = "Molodezhnaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Октябрьская" do
    cyrilic = "Октябрьская"
    transliteration = "Oktyabrskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Ольховая" do
    cyrilic = "Ольховая"
    transliteration = "Olkhovaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Парк Победы" do
    cyrilic = "Парк Победы"
    transliteration = "Park Pobedy"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Площадь Ильича" do
    cyrilic = "Площадь Ильича"
    transliteration = "Ploschad Ilyicha"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Площадь Революции" do
    cyrilic = "Площадь Революции"
    transliteration = "Ploschad Revolyutsii"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Пятницкое шоссе" do
    cyrilic = "Пятницкое шоссе"
    transliteration = "Pyatnitskoe shosse"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Румянцево" do
    cyrilic = "Румянцево"
    transliteration = "Rumyantsevo"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Саларьево" do
    cyrilic = "Саларьево"
    transliteration = "Salaryevo"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Семёновская" do
    cyrilic = "Семёновская"
    transliteration = "Semenovskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Сходненская" do
    cyrilic = "Сходненская"
    transliteration = "Skhodnenskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Текстильщики" do
    cyrilic = "Текстильщики"
    transliteration = "Tekstilschiki"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Тёплый стан" do
    cyrilic = "Тёплый стан"
    transliteration = "Teply stan"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Третьяковская" do
    cyrilic = "Третьяковская"
    transliteration = "Tretyakovskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Тропарёво" do
    cyrilic = "Тропарёво"
    transliteration = "Troparevo"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Фонвизинская" do
    cyrilic = "Фонвизинская"
    transliteration = "Fonvizinskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Чистые пруды" do
    cyrilic = "Чистые пруды"
    transliteration = "Chistye prudy"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Шоссе Энтузиастов" do
    cyrilic = "Шоссе Энтузиастов"
    transliteration = "Shosse Entuziastov"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Щёлковская" do
    cyrilic = "Щёлковская"
    transliteration = "Schelkovskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Электрозаводская" do
    cyrilic = "Электрозаводская"
    transliteration = "Elektrozavodskaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Юго-Западная" do
    cyrilic = "Юго-Западная"
    transliteration = "Yugo-Zapadnaya"

    Iuliia::Mosmetro.translate(cyrilic).should eq(transliteration)
  end
end
