# Generated from Iuliia schemas. See `Iuliia::SchemaImporter`.
# 2022-01-09 03:48:22 UTC
#
# DO NOT edit this file directly.
#
# ----------------------------------------------------------------------------
# Iuliia
# https://github.com/nalgeon/iuliia
# ----------------------------------------------------------------------------
#
# MIT License
#
# Copyright (c) 2020 Anton Zhiyanov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

require "../spec_helper"

describe Iuliia::Wikipedia do
  it "transliterates Юлия, съешь ещё этих мягких французских булок из Йошкар-Олы, да выпей алтайского чаю" do
    cyrilic = "Юлия, съешь ещё этих мягких французских булок из Йошкар-Олы, да выпей алтайского чаю"
    transliteration = "Yuliya, syesh yeshchyo etikh myagkikh frantsuzskikh bulok iz Yoshkar-Oly, da vypey altayskogo chayu"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Россия, город Йошкар-Ола, улица Яна Крастыня" do
    cyrilic = "Россия, город Йошкар-Ола, улица Яна Крастыня"
    transliteration = "Rossiya, gorod Yoshkar-Ola, ulitsa Yana Krastynya"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Ельцин" do
    cyrilic = "Ельцин"
    transliteration = "Yeltsin"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Раздольное" do
    cyrilic = "Раздольное"
    transliteration = "Razdolnoye"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Юрьев" do
    cyrilic = "Юрьев"
    transliteration = "Yuryev"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Белкин" do
    cyrilic = "Белкин"
    transliteration = "Belkin"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Бийск" do
    cyrilic = "Бийск"
    transliteration = "Biysk"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Подъярский" do
    cyrilic = "Подъярский"
    transliteration = "Podyarsky"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Мусийкъонгийкоте" do
    cyrilic = "Мусийкъонгийкоте"
    transliteration = "Musiykyongiykote"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Давыдов" do
    cyrilic = "Давыдов"
    transliteration = "Davydov"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Усолье" do
    cyrilic = "Усолье"
    transliteration = "Usolye"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Выхухоль" do
    cyrilic = "Выхухоль"
    transliteration = "Vykhukhol"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Дальнегорск" do
    cyrilic = "Дальнегорск"
    transliteration = "Dalnegorsk"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Ильинский" do
    cyrilic = "Ильинский"
    transliteration = "Ilyinsky"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Красный" do
    cyrilic = "Красный"
    transliteration = "Krasny"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Великий" do
    cyrilic = "Великий"
    transliteration = "Veliky"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end

  it "transliterates Набережные Челны" do
    cyrilic = "Набережные Челны"
    transliteration = "Naberezhnye Chelny"

    Iuliia::Wikipedia.translate(cyrilic).should eq(transliteration)
  end
end
